test 5

diff --git a/.github/workflows/rviz2_test.yml b/.github/workflows/rviz2_test.yml
--- a/.github/workflows/rviz2_test.yml
+++ b/.github/workflows/rviz2_test.yml
@@ -23,7 +23,7 @@ jobs:
 
       - name: Install dependencies and RViz2
         run: |
-          sudo apt install ros-humble-rviz2 -y
+          sudo apt install ros-humble-rviz2 xvfb -y
           source /opt/ros/humble/setup.bash
           chmod +x setup.sh
           ./setup.sh
@@ -39,9 +39,9 @@ jobs:
             echo "Error: RViz2 binary not found!" && exit 1
           fi
           echo "RViz2 binary located at: $(command -v rviz2)"
-          rviz2 --version || (echo "Error: RViz2 version command failed!" && exit 1)
+          xvfb-run -a rviz2 --version || (echo "Error: RViz2 version command failed!" && exit 1)
 
       - name: Test RViz2 command
         run: |
           source /opt/ros/humble/setup.bash
-          rviz2 --version || (echo "Error: RViz2 version command failed!" && exit 1)
+          xvfb-run -a rviz2 --version || (echo "Error: RViz2 version command failed!" && exit 1)
